# from <https://github.com/taocpp/PEGTL/blob/master/.travis.yml>
language: cpp

os: linux
dist: xenial
sudo: false

git:
  depth: 1

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-4.9
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-5
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-6
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-7
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-8
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-3.8']
          packages: ['clang-3.8', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-3.8
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-3.9']
          packages: ['clang-3.9', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-3.9
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-4.0']
          packages: ['clang-4.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-4.0
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
          packages: ['clang-5.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-5.0
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
          packages: ['clang-6.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-6.0
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
          packages: ['clang-7', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-7
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-4.9
        - GPG_COMPATIBLE=True

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-5
        - GPG_COMPATIBLE=True

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-6
        - GPG_COMPATIBLE=True

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-7
        - GPG_COMPATIBLE=True

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov']
      env:
        - CXX_COMPILER=g++-8
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-3.8']
          packages: ['clang-3.8', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-3.8
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-3.9']
          packages: ['clang-3.9', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-3.9
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-4.0']
          packages: ['clang-4.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-4.0
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
          packages: ['clang-5.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-5.0
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
          packages: ['clang-6.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-6.0
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
          packages: ['clang-7', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake', 'python-pip', 'lcov', 'llvm']
      env:
        - CXX_COMPILER=clang++-7
        - GPG_COMPATIBLE=True

before_install:
  - pip install --user cpp-coveralls

before_script:
  - export CXX=${CXX_COMPILER}
  - export GTEST_COLOR=1
  - export OPENPGP_PATH=/tmp/OpenPGP

script:
  # normal build and test
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=${OPENPGP_PATH} -DCMAKE_BUILD_TYPE=Debug -DGPG_COMPATIBLE="${GPG_COMPATIBLE}" -DCODE_COVERAGE=On
  - cmake --build .
  - ctest --verbose

  # rebuild the cli as a standalone application using the installed files
  - make install
  - ${CXX} -Wall -std=c++11 -I${OPENPGP_PATH}/include ../cli/main.cpp ../cli/modules/module.cpp -L${OPENPGP_PATH}/lib -lOpenPGP -lgmp -lgmpxx -lbz2 -lz -o OpenPGP -Wl,-rpath="$(realpath ${OPENPGP_PATH}/lib)"
  - ./OpenPGP

after_success:
  - if [[ "${CXX_COMPILER}" =~ "g++-"     ]]; then export GCOV_TOOL="gcov-${CXX_COMPILER##*-}"; fi
  - if [[ "${CXX_COMPILER}" =~ "clang++-" ]]; then export GCOV_TOOL="$(realpath ../contrib/lcov/clang.sh)"; fi
  - ~/.local/bin/cpp-coveralls --gcov "${GCOV_TOOL}" --root .. --build-root . --include include --include src --include cli --exclude usr --exclude tests --exclude cli/tests --gcov-options '\-lp' &> /dev/null